services:
  mongo:
    image: mongo:latest 
    restart: unless-stopped
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongo_shelter:/data/db
    environment:
      MONGO INITDB_ROOT_USERNAME:${DB_USER}
      MONGO INITDB_ROOT_PASSWORD:${DB_PASSWORD}
      MONGO INITDB_ROOT_DATABASE:${DB_NAME}
      
    backend:
      build: .
      container_name: ${APP_HOST}
      restart: unless-stopped
      ports:
        - ${APP_PORT}:3000
      volumes:
        - ./:/app
        - node_modules:/app/node_modules
volumes:
  node_modules:
  mongo_shelter: